export const GameConfig = {
	CANVAS_WIDTH: 800,
	CANVAS_HEIGHT: 600,
	WINNING_SCORE: 5,

	BASE_BALL_SPEED_FACTOR: 100,
	PADDLE_SPEED_FACTOR: 100,
	BALL_SPEEDUP_FACTOR: 1.05,
	MAX_BALL_SPEED: 800,

	MIN_VERTICAL_SPEED: 2,
	MAX_ANGLE: Math.PI / 4,
	MIN_ANGLE: -Math.PI / 4,

	BLINK_INTERVAL: 700,

	DEFAULT_BALL_SPEED: 3,
	DEFAULT_BALL_RADIUS: 10,
	DEFAULT_PADDLE_LENGTH: 100,
	DEFAULT_PADDLE_WIDTH: 10,
	DEFAULT_PADDLE_SPEED: 5,
	DEFAULT_MAP: 'default',
	DEFAULT_POWERUPS: false,
	DEFAULT_MAX_SCORE: 3,

	TEST_MODE: false,
	TARGET_FPS: 60,
	BROADCAST_RATE: 30,
};
