export const GameConfig = {
	CANVAS_WIDTH: 800,
	CANVAS_HEIGHT: 600,
	WINNING_SCORE: 5,
	MIN_VERTICAL_SPEED: 2,
	MAX_ANGLE: Math.PI / 4,
	MIN_ANGLE: -Math.PI / 4,
	BLINK_INTERVAL: 700,
	DEFAULT_BALL_SPEED: 4,
	DEFAULT_PADDLE_LENGTH: 100,
	DEFAULT_PADDLE_SPEED: 5,
	DEFAULT_MAP: 'default',
	DEFAULT_POWERUPS: false,
};

export const TEST_MODE = true;
